export const THEME_VISUAL_FIELDS = [
    'bg_color',
    'surface_color',
    'text_color',
    'secondary_text_color',
    'border_color',
    'accent_color',
    'font_family_display',
    'font_family_body',
    'effect_preset',
    'effect_intensity',
    'background_style',
    'gradient_colors',
    'gradient_angle',
    'gradient_intensity',
];

const SOLID_RECIPE_DEFAULTS = {
    background_style: 'solid',
    gradient_colors: [],
    gradient_angle: 135,
    gradient_intensity: 'medium',
};

export const DEPRECATED_DEFAULT_THEME_NAMES = [
    'Arctic Frost',
    'Botanical Garden',
    'Desert Rose',
    'Forest Canopy',
    'Golden Hour',
    'Midnight Galaxy',
    'Modern Minimal',
    'Ocean Depths',
    'Rose',
    'Sunset Blvd',
    'Tech Innovation',
];

export const DEFAULT_THEME_REPLACEMENTS = {
    'Arctic Frost': 'Deep Current',
    'Modern Minimal': 'Manuscript',
    'Tech Innovation': 'Signal Glass',
};

const DEFAULT_THEME_CATALOG = [
    {
        collection: 'foundation',
        name: 'Riven',
        bg_color: '#162a31',
        surface_color: '#1e3840',
        text_color: '#e4ddd0',
        secondary_text_color: '#8fa6a8',
        border_color: '#233e46',
        accent_color: '#deb96a',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 1,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Riven Light',
        bg_color: '#f5f0e8',
        surface_color: '#ffffff',
        text_color: '#1e3840',
        secondary_text_color: '#6b7d7f',
        border_color: '#ddd5c8',
        accent_color: '#deb96a',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Manuscript',
        bg_color: '#f3eee3',
        surface_color: '#fffaf1',
        text_color: '#211b16',
        secondary_text_color: '#75695b',
        border_color: '#d8cdbb',
        accent_color: '#8a9b55',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Lora',
        effect_preset: 'dust',
        effect_intensity: 'soft',
        background_style: 'gradient',
        gradient_colors: ['#f3eee3', '#fffaf1', '#d9c8ac'],
        gradient_angle: 145,
        gradient_intensity: 'soft',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Deep Current',
        bg_color: '#071a1d',
        surface_color: '#0f2a2d',
        text_color: '#e7f2eb',
        secondary_text_color: '#8ca9a5',
        border_color: '#1f4546',
        accent_color: '#7bcbb8',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        background_style: 'gradient',
        gradient_colors: ['#061013', '#0a2c31', '#124d4c'],
        gradient_angle: 160,
        gradient_intensity: 'rich',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Signal Glass',
        bg_color: '#081114',
        surface_color: '#101d20',
        text_color: '#e8f3ef',
        secondary_text_color: '#90a6a3',
        border_color: '#26383a',
        accent_color: '#8be2d1',
        font_family_display: 'JetBrains Mono',
        font_family_body: 'Space Grotesk',
        effect_preset: 'grid',
        effect_intensity: 'medium',
        background_style: 'gradient',
        gradient_colors: ['#071013', '#102026', '#17353a'],
        gradient_angle: 135,
        gradient_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Sage Temple',
        bg_color: '#0f1b17',
        surface_color: '#16261f',
        text_color: '#edf4ee',
        secondary_text_color: '#93aa9e',
        border_color: '#2a3b33',
        accent_color: '#7dde82',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Dawn Ember',
        bg_color: '#1a0d0a',
        surface_color: '#26130f',
        text_color: '#fff1ea',
        secondary_text_color: '#cda996',
        border_color: '#4a241b',
        accent_color: '#ff7a45',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Misty Shore',
        bg_color: '#101a22',
        surface_color: '#16242d',
        text_color: '#eef5f8',
        secondary_text_color: '#99acb6',
        border_color: '#273a46',
        accent_color: '#9ec7d9',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Amber Lantern',
        bg_color: '#1b120b',
        surface_color: '#261810',
        text_color: '#fff4e8',
        secondary_text_color: '#d2b494',
        border_color: '#4a2d1d',
        accent_color: '#f5a623',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Moonlit Cove',
        bg_color: '#0d1322',
        surface_color: '#141c31',
        text_color: '#f0f4ff',
        secondary_text_color: '#9ea9c8',
        border_color: '#27314e',
        accent_color: '#9db4ff',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Rain Garden',
        bg_color: '#0d1a1e',
        surface_color: '#14252b',
        text_color: '#edf7f6',
        secondary_text_color: '#96afb2',
        border_color: '#244149',
        accent_color: '#78c7c4',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Cherry Blossom',
        bg_color: '#1b1320',
        surface_color: '#271c2f',
        text_color: '#fff0f8',
        secondary_text_color: '#d6adc4',
        border_color: '#4a314e',
        accent_color: '#f28bb9',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Lavender Dusk',
        bg_color: '#171226',
        surface_color: '#221a34',
        text_color: '#efe7ff',
        secondary_text_color: '#b6a4e6',
        border_color: '#30244b',
        accent_color: '#b89bf3',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        ...SOLID_RECIPE_DEFAULTS,
        is_active: 0,
        is_default: 1,
    },
];

export const FOUNDATION_THEME_NAMES = DEFAULT_THEME_CATALOG
    .filter((theme) => theme.collection === 'foundation')
    .map((theme) => theme.name);

export function getDefaultThemes() {
    return DEFAULT_THEME_CATALOG.map(({ collection: _collection, ...theme }) => ({ ...theme }));
}
