export const THEME_VISUAL_FIELDS = [
    'bg_color',
    'surface_color',
    'text_color',
    'secondary_text_color',
    'border_color',
    'accent_color',
    'font_family_display',
    'font_family_body',
    'effect_preset',
    'effect_intensity',
];

export const DEPRECATED_DEFAULT_THEME_NAMES = [
    'Botanical Garden',
    'Desert Rose',
    'Forest Canopy',
    'Golden Hour',
    'Midnight Galaxy',
    'Ocean Depths',
    'Rose',
    'Sunset Blvd',
];

const DEFAULT_THEME_CATALOG = [
    {
        collection: 'foundation',
        name: 'Riven',
        bg_color: '#162a31',
        surface_color: '#1e3840',
        text_color: '#e4ddd0',
        secondary_text_color: '#8fa6a8',
        border_color: '#233e46',
        accent_color: '#deb96a',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 1,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Riven Light',
        bg_color: '#f5f0e8',
        surface_color: '#ffffff',
        text_color: '#1e3840',
        secondary_text_color: '#6b7d7f',
        border_color: '#ddd5c8',
        accent_color: '#deb96a',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Arctic Frost',
        bg_color: '#eaf2f6',
        surface_color: '#f9fdff',
        text_color: '#163038',
        secondary_text_color: '#607983',
        border_color: '#cad8de',
        accent_color: '#89c3d4',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Space Grotesk',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Modern Minimal',
        bg_color: '#efeae3',
        surface_color: '#fbf8f3',
        text_color: '#181512',
        secondary_text_color: '#70665d',
        border_color: '#d7cec2',
        accent_color: '#c88259',
        font_family_display: 'Space Grotesk',
        font_family_body: 'Space Grotesk',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'foundation',
        name: 'Tech Innovation',
        bg_color: '#061317',
        surface_color: '#0b1d22',
        text_color: '#e7faf8',
        secondary_text_color: '#88a7ab',
        border_color: '#1f3a40',
        accent_color: '#71d6ca',
        font_family_display: 'JetBrains Mono',
        font_family_body: 'Space Grotesk',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Sage Temple',
        bg_color: '#0f1b17',
        surface_color: '#16261f',
        text_color: '#edf4ee',
        secondary_text_color: '#93aa9e',
        border_color: '#2a3b33',
        accent_color: '#7dde82',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Dawn Ember',
        bg_color: '#1a0d0a',
        surface_color: '#26130f',
        text_color: '#fff1ea',
        secondary_text_color: '#cda996',
        border_color: '#4a241b',
        accent_color: '#ff7a45',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Misty Shore',
        bg_color: '#101a22',
        surface_color: '#16242d',
        text_color: '#eef5f8',
        secondary_text_color: '#99acb6',
        border_color: '#273a46',
        accent_color: '#9ec7d9',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Amber Lantern',
        bg_color: '#1b120b',
        surface_color: '#261810',
        text_color: '#fff4e8',
        secondary_text_color: '#d2b494',
        border_color: '#4a2d1d',
        accent_color: '#f5a623',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Moonlit Cove',
        bg_color: '#0d1322',
        surface_color: '#141c31',
        text_color: '#f0f4ff',
        secondary_text_color: '#9ea9c8',
        border_color: '#27314e',
        accent_color: '#9db4ff',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Rain Garden',
        bg_color: '#0d1a1e',
        surface_color: '#14252b',
        text_color: '#edf7f6',
        secondary_text_color: '#96afb2',
        border_color: '#244149',
        accent_color: '#78c7c4',
        font_family_display: 'Instrument Serif',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Cherry Blossom',
        bg_color: '#1b1320',
        surface_color: '#271c2f',
        text_color: '#fff0f8',
        secondary_text_color: '#d6adc4',
        border_color: '#4a314e',
        accent_color: '#f28bb9',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
    {
        collection: 'professional',
        name: 'Lavender Dusk',
        bg_color: '#171226',
        surface_color: '#221a34',
        text_color: '#efe7ff',
        secondary_text_color: '#b6a4e6',
        border_color: '#30244b',
        accent_color: '#b89bf3',
        font_family_display: 'Cormorant Garamond',
        font_family_body: 'Lora',
        effect_preset: 'auto',
        effect_intensity: 'medium',
        is_active: 0,
        is_default: 1,
    },
];

export const FOUNDATION_THEME_NAMES = DEFAULT_THEME_CATALOG
    .filter((theme) => theme.collection === 'foundation')
    .map((theme) => theme.name);

export function getDefaultThemes() {
    return DEFAULT_THEME_CATALOG.map(({ collection, ...theme }) => ({ ...theme }));
}
