CREATE TABLE IF NOT EXISTS public.feedback_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_favorited BOOLEAN NOT NULL DEFAULT FALSE,
  considering_notified_at TIMESTAMPTZ,
  considering_notified_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.user_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  dismissed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS feedback_submissions_created_at_idx
  ON public.feedback_submissions (created_at DESC);

CREATE INDEX IF NOT EXISTS feedback_submissions_favorited_created_at_idx
  ON public.feedback_submissions (is_favorited, created_at DESC);

CREATE INDEX IF NOT EXISTS user_notifications_user_created_at_idx
  ON public.user_notifications (user_id, created_at DESC);

ALTER TABLE public.feedback_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS feedback_submissions_select_own ON public.feedback_submissions;
CREATE POLICY feedback_submissions_select_own ON public.feedback_submissions
  FOR SELECT USING (user_id = public.get_app_user_id());

DROP POLICY IF EXISTS feedback_submissions_insert_own ON public.feedback_submissions;
CREATE POLICY feedback_submissions_insert_own ON public.feedback_submissions
  FOR INSERT WITH CHECK (user_id = public.get_app_user_id());

DROP POLICY IF EXISTS user_notifications_select_own ON public.user_notifications;
CREATE POLICY user_notifications_select_own ON public.user_notifications
  FOR SELECT USING (user_id = public.get_app_user_id());

DROP POLICY IF EXISTS user_notifications_update_own ON public.user_notifications;
CREATE POLICY user_notifications_update_own ON public.user_notifications
  FOR UPDATE USING (user_id = public.get_app_user_id())
  WITH CHECK (user_id = public.get_app_user_id());
